#!/bin/bash
action=$1
target=$2
args=$@

DE_BASE=/opt/
export COMPOSE_HTTP_TIMEOUT=180

compose_files="-f docker-compose.yml -f docker-compose-kettle-doris.yml"
if [[ "${build_in_database}" == "y" ]];then
  compose_files="${compose_files} -f docker-compose-mysql.yml"
fi

function usage() {
   echo "DATAEASE 控制脚本"
   echo
   echo "Usage: "
   echo "  ./dectl [COMMAND] [ARGS...]"
   echo "  ./dectl --help"
   echo
   echo "Commands: "
   echo "  status    查看 DATAEASE 服务运行状态"
   echo "  start     启动 DATAEASE 服务"
   echo "  stop      停止 DATAEASE 服务"
   echo "  restart   重启 DATAEASE 服务"
   echo "  reload    重新加载 DATAEASE 服务"
   echo "  uninstall 卸载 DATAEASE 服务"
   echo "  upgrade   升级 DATAEASE 服务"
   echo "  version   查看 DATAEASE 版本信息"
}

function status() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} ps
}
function start() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} start ${target}
}
function stop() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} stop ${target}
}
function restart() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} restart ${target}
}
function reload() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} up -d
}
function uninstall() {
   echo
   cd ${DE_BASE}/dataease; docker-compose ${compose_files} ${module_compose_files} down -v ${target}
}
function version() {
   echo
   cat ${DE_BASE}/dataease/conf/version
}
function upgrade() {
   echo
   latest_version=`curl -s https://api.github.com/repos/dataease/dataease/releases/latest | grep -e "\"tag_name\"" | sed -r 's/.*: "(.*)",/\1/'`
   current_version=$(cat ${DE_BASE}/dataease/conf/version)

   if [ "${latest_version}" = "" ];then
      echo "未获取到最新版本"
      exit 1
   elif [ "${latest_version}" = "${current_version}" ];then
      echo "最新版本与当前版本一致,退出升级过程"
      exit 0
   else
      echo -e "\e[32m 检测到GitHub上最新版本为\e[1;33m${latest_version}\e[0;32m 即将执行在线升级...\e[0m"
   fi
   sleep 2s
   wget -nv -T 60 -t 1 --no-check-certificate https://github.com/dataease/dataease/releases/download/${latest_version}/dataease-release-${latest_version}.tar.gz -O /tmp/dataease-release-${latest_version}.tar.gz
   if [ $? -ne 0 ]; then
      echo -e "\e[31m升级失败:连接GitHub超时！\n可手动下载升级包，然后执行\e[1;33m /bin/bash install.sh \e[0;31m离线升级，也可以重新执行一次 dectl upgrade 命令。\e[0m"
      return 2
   fi
   cd /tmp
   tar zxvf dataease-release-${latest_version}.tar.gz
   cd dataease-release-${latest_version}
   /bin/bash install.sh
   rm -rf /tmp/dataease-release-${latest_version}
}

function main() {
    case "${action}" in
      status)
         status
         ;;
      start)
         start
         ;;
      stop)
         stop
         ;;
      restart)
         restart
         ;;
      reload)
         reload
         ;;
      uninstall)
         uninstall
         ;;
      upgrade)
         upgrade
         ;;
      version)
         version
         ;;
      help)
         usage
         ;;
      --help)
         usage
         ;;
      *)
         echo "不支持的参数，请使用 help 或 --help 参数获取帮助"
    esac
}
main